### ISSUE TITLE
Status route

### ISSUE THREAD

**Issue by janrenz** [MatthiasWiesner/antivirus_check_service#1]
I would like to have a status route with the following information:
- virus-definition-file-last_updated

**Comment by MatthiasWiesner** [comment]
@janrenz if the service is running on the same vm, this information can be fetched from the logfile or `clamav-freshclam` (the daemon, which keeps the signatures up to date) can be configured with a _on-success_ hook (preferable way). 
But If we want to use clamav, installed in this [docker container](https://hub.docker.com/r/mkodockx/docker-clamav/), we have to adjust this docker container.

**Comment by MatthiasWiesner** [comment]
Is implemented now. See README for details
